---
### Flask Server Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-flask-otel-k8s
spec:
  selector:
    matchLabels:
      name: server-flask-otel-k8s
  template:
    metadata:
      labels:
        name: server-flask-otel-k8s
    spec:
      containers:
      - name: server-flask-otel-k8s
        image: docker.io/stevelsplunk/splk-python
        ports:
          - name: http
            containerPort: 5000
        env:
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: deployment.environment=apm-workshop
        - name: OTEL_SERVICE_NAME
          value: server-flask-otel-k8s
        - name: SPLUNK_OTEL_AGENT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_JAEGER_ENDPOINT
          value: http://$(SPLUNK_OTEL_AGENT):9080/v1/trace
        - name: OTEL_TRACES_EXPORTER
          value: jaeger-thrift-splunk
        command: ["/bin/sh"]
        args: ["run-server.sh"]
---
### Flask Server Service
apiVersion: v1
kind: Service
metadata:
  name: server-flask-otel-k8s
spec:
  selector:
    name: server-flask-otel-k8s
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
### Python Requests Pod
apiVersion: v1
kind: Pod
metadata:
  name: client-py-otel-k8s
spec:
  containers:
  - name: client-py-otel-k8s
    image: docker.io/stevelsplunk/splk-python
    env:
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: deployment.environment=apm-workshop
    - name: OTEL_SERVICE_NAME
      value: client-py-otel-k8s
    - name: SPLUNK_OTEL_AGENT
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: OTEL_EXPORTER_JAEGER_ENDPOINT
      value: http://$(SPLUNK_OTEL_AGENT):9080/v1/trace
    - name: OTEL_TRACES_EXPORTER
      value: jaeger-thrift-splunk
    command: ["/bin/sh"]
    args: ["run-client.sh"]