clusterName: YOURCLUSTERHERE
splunkRealm: YOUREREALMHERE
splunkAccessToken: YOURTOKENHERE

otelAgent:
  config:
    receivers:
      smartagent/redis:    
        type: collectd/redis
        host: redis
        port: 6379
    service:
      pipelines:
        metrics:
          receivers:
            - hostmetrics
            - kubeletstats
            - receiver_creator
            - smartagent/redis